### ISSUE TITLE
Support Google Fonts

### ISSUE THREAD

**Issue by davelab6** [manolosavi/xFonts#3]
The Google Fonts developer's API will allow you to integrate Google Fonts into the app by default

**Comment by chockenberry** [comment]
The problem here is that you then have to give the user a way to navigate thousands of fonts and weights. The web feels like a better way to do this, and you can download the fonts you like to your own cloud storage.

Fontcase's strength is getting your favorite fonts onto the device, not finding new fonts.

**Comment by manolosavi** [comment]
Yea @chockenberry said it well, Fontcase already supports Google fonts if you just browse the fonts on the web and download them to your device. Gonna close this issue.
